//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.sample.com/", ConfigurationName="HelloWorld")]
public interface HelloWorld
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://ws.sample.com/HelloWorld/getHelloWorldAsStringRequest", ReplyAction="http://ws.sample.com/HelloWorld/getHelloWorldAsStringResponse")]
    [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
    [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
    string getHelloWorldAsString(string arg0);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://ws.sample.com/HelloWorld/getHelloWorldAsStringRequest", ReplyAction="http://ws.sample.com/HelloWorld/getHelloWorldAsStringResponse")]
    [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
    System.Threading.Tasks.Task<string> getHelloWorldAsStringAsync(string arg0);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface HelloWorldChannel : HelloWorld, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class HelloWorldClient : System.ServiceModel.ClientBase<HelloWorld>, HelloWorld
{
    
    public HelloWorldClient()
    {
    }
    
    public HelloWorldClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public HelloWorldClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public HelloWorldClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public HelloWorldClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public string getHelloWorldAsString(string arg0)
    {
        return base.Channel.getHelloWorldAsString(arg0);
    }
    
    public System.Threading.Tasks.Task<string> getHelloWorldAsStringAsync(string arg0)
    {
        return base.Channel.getHelloWorldAsStringAsync(arg0);
    }
}
