package com.sample.endpoint;

import static java.lang.System.out;
import javax.xml.ws.Endpoint;
import com.sample.ws.HelloWorldImpl;

//Endpoint publisher
public class HelloWorldPublisher {
    public static void main(String[] args) {
        out.println("Publishing . . .");
        Endpoint.publish("http://localhost:9999/ws/hello", new HelloWorldImpl());
        out.println("Published to endpoint: http://localhost:9999/ws/hello");
        out.println("Access the WSDL generated by the deployed web service via URL:");
        out.println("http://localhost:9999/ws/hello?wsdl");
    }
}