package endpoint;

import static java.lang.System.out;
import javax.xml.ws.Endpoint;
import ws.JavaWebServiceImp;

public class JavaWebServicePublisher {
    public static void main(String[] args) {
        out.println("Publishing . . .");
        Endpoint.publish("http://localhost:8000/JavaWebService", new JavaWebServiceImp());
        out.println("Published to endpoint: http://localhost:8000/JavaWebService");
        out.println("Access the WSDL generated by the deployed web service via URL:");
        out.println("http://localhost:8000/JavaWebService?wsdl");
    }
}